model_list:
  - model_name: gemini-flash-free
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/FREE_GEMINI_API_KEY
      rpm: 5
      tpm: 250000
  - model_name: gemini-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY
      rpm: 1000
      tpm: 1000000
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY
      rpm: 150
      tpm: 2000000
  - model_name: gemini-flash-image
    litellm_params:
      model: gemini/gemini-2.5-flash-image
      api_key: os.environ/GEMINI_API_KEY
    model_info:
      mode: image_generation
  - model_name: groq-llama-3.3-70B
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: os.environ/GROQ_API_KEY
      rpm: 1000
      tpm: 300000
  - model_name: groq-llama-3.1-8B
    litellm_params:
      model: groq/llama-3.1-8b-instant
      api_key: os.environ/GROQ_API_KEY
      rpm: 1000
      tpm: 250000
  - model_name: groq-gpt-oss-120b
    litellm_params:
      model: groq/openai/gpt-oss-120b
      api_key: os.environ/GROQ_API_KEY
      rpm: 1000
      tpm: 250000
  - model_name: groq-gpt-oss-20b
    litellm_params:
      model: groq/openai/gpt-oss-20b
      api_key: os.environ/GROQ_API_KEY
      rpm: 1000
      tpm: 250000
  - model_name: groq-whisper-large-v3-turbo
    litellm_params:
      model: groq/whisper-large-v3-turbo
      api_key: os.environ/GROQ_API_KEY
      rpm: 400
  - model_name: claude-haiku
    litellm_params:
      model: anthropic/claude-haiku-4-5-20251001
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-sonnet
    litellm_params:
      model: anthropic/claude-sonnet-4-5-20250929
      api_key: os.environ/ANTHROPIC_API_KEY

general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true
litellm_settings:
  drop_params: true
