global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO
  filePath: /logs/traefik.log

accessLog:
  filePath: /logs/access.log
  bufferingSize: 100

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    forwardedHeaders:
      trustedIPs:
        - 100.64.0.0/10
        - 127.0.0.1/32
        - 10.0.0.0/24
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    forwardedHeaders:
      trustedIPs:
        - 100.64.0.0/10
        - 127.0.0.1/32
        - 10.0.0.0/24

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    network: yohnet

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${CF_API_EMAIL}
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10 

# http:
#   middlewares:
#     tinyauth:
#       forwardAuth:
#         address: http://tinyauth:3000/api/auth/caddy  # Matches your tinyauth_forwarder
#         trustForwardHeader: true
#     webdav-auth:
#       basicAuth:
#         users:
#         - "yoh268:$2y$05$aGDdyUrV6sZK2jJXYYMbq.2A2OctRr0KwOfTt2B8jsvBIbn57/UaG"  # Your existing hash

